"""empty message

Revision ID: 039d5e1c9995
Revises: 306c1d488c90
Create Date: 2024-04-25 07:59:33.997873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039d5e1c9995'
down_revision: Union[str, None] = '306c1d488c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('auditor1', sa.String(), nullable=True))
    op.add_column('question', sa.Column('auditor2', sa.String(), nullable=True))
    op.add_column('question', sa.Column('audit_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'audit_type')
    op.drop_column('question', 'auditor2')
    op.drop_column('question', 'auditor1')
    # ### end Alembic commands ###
