"""empty message

Revision ID: 2d0f3753a5cb
Revises: 6b4de71a8478
Create Date: 2024-04-29 12:00:02.256697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0f3753a5cb'
down_revision: Union[str, None] = '6b4de71a8478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'company')
    # ### end Alembic commands ###
