"""empty message

Revision ID: 2e0548c5d0a8
Revises: 5d22b6227fc7
Create Date: 2024-08-20 15:24:14.498476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0548c5d0a8'
down_revision: Union[str, None] = '5d22b6227fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('audit_year_start', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('audit_year_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'audit_year_end')
    op.drop_column('question', 'audit_year_start')
    # ### end Alembic commands ###
