"""empty message

Revision ID: 54a3dcdf640a
Revises: 039d5e1c9995
Create Date: 2024-04-25 08:45:20.850084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a3dcdf640a'
down_revision: Union[str, None] = '039d5e1c9995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('region', sa.String(), nullable=True))
    op.add_column('question', sa.Column('production', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'production')
    op.drop_column('question', 'region')
    # ### end Alembic commands ###
