"""empty message

Revision ID: 5d22b6227fc7
Revises: 2d0f3753a5cb
Create Date: 2024-04-29 14:59:23.096159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d22b6227fc7'
down_revision: Union[str, None] = '2d0f3753a5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('pdf_file_name', sa.String(), nullable=True))
    op.add_column('question', sa.Column('pdf_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'pdf_file_path')
    op.drop_column('question', 'pdf_file_name')
    # ### end Alembic commands ###
