"""empty message

Revision ID: 6b4de71a8478
Revises: a0a8fe4d4fa3
Create Date: 2024-04-26 08:54:44.730277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4de71a8478'
down_revision: Union[str, None] = 'a0a8fe4d4fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('auditor3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'auditor3')
    # ### end Alembic commands ###
