"""empty message

Revision ID: a0a8fe4d4fa3
Revises: 54a3dcdf640a
Create Date: 2024-04-26 08:27:45.822831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a8fe4d4fa3'
down_revision: Union[str, None] = '54a3dcdf640a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('audit_date_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'audit_date_end')
    # ### end Alembic commands ###
